openapi: 3.0.0
info:
  title: Ping API
  version: 1.0.0
  description: Returns "pong" for GET /ping
servers:
  - url: http://localhost:8000
paths:
  /ping:
    get:
      description: Returns "pong"
      responses:
        '200':
          description: successful
          content:
            text/plain:
              schema:
                type: string
                example: pong
