
openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
  description: Manage users with pagination
servers:
  - url: http://localhost:8000
paths:
  /users:
    get:
      description: Retrieve a list of users with pagination
      parameters:
        - name: page
          in: query
          required: true
          description: Page number
          schema:
            type: integer
          example: 1
        - name: size
          in: query
          required: true
          description: Number of users per page
          schema:
            type: integer
          example: 20
      responses:
        '200':
          description: List of users retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    email:
                      type: string
              example:
                - id: 1
                  name: Alice
                  email: alice@example.com
                - id: 2
                  name: Bob
                  email: bob@example.com
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Bad types for provided query parameters"
