
openapi: 3.0.0
info:
  title: Orders & Products API
  version: 1.0.0
  description: Manage products and customer orders (with authentication)
servers:
  - url: http://localhost:8000
tags:
  - name: Products
    description: Product-related endpoints
  - name: Orders
    description: Order-related endpoints
paths:
  /products:
    get:
      tags:
        - Products
      description: Retrieve all products
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /orders:
    get:
      tags:
        - Orders
      description: Retrieve a paginated list of orders
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
        - Orders
      description: Create a new order (requires Basic Authentication)
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            example:
              identifier: 101
              customer_name: "John Doe"
              creation_datetime: "2025-08-24T10:00:00Z"
              total_amount: 250.75
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  parameters:
    page:
      name: page
      in: query
      required: false
      description: Page number
      schema:
        type: integer
      example: 1
    size:
      name: size
      in: query
      required: false
      description: Number of items per page
      schema:
        type: integer
      example: 20
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
    Order:
      type: object
      properties:
        identifier:
          type: integer
        customer_name:
          type: string
        creation_datetime:
          type: string
          format: date-time
        total_amount:
          type: number
          format: float
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
